---
# Research and Documentation
# Paperless-ngx: https://docs.paperless-ngx.com/
# - Open source document management system
# - PostgreSQL database: https://www.postgresql.org/
# - Redis broker: https://redis.io/
# - Gotenberg (document conversion): https://gotenberg.dev/
# - Apache Tika (text extraction): https://tika.apache.org/

paperless_version: "latest"
redis_version: "7"
postgres_version: "16"
gotenberg_version: "8.7"
tika_version: "latest"

# External port
paperless_port: 8000

# Volume paths
paperless_folder: "{{ docker_storage_folder }}/paperless"

# Feature flags
paperless_configure_dns: true
paperless_configure_proxy: true
paperless_configure_homepage: true
