---
- name: Start Omada SDN Controller
  community.docker.docker_compose_v2:
    project_src: "{{ omada_sdn_folder }}"
    state: restarted
    remove_orphans: true

- name: Restart Homepage
  community.docker.docker_compose_v2:
    project_src: "{{ homepage_folder }}"
    state: restarted
  delegate_to: "{{ groups['homepage_host'][0] }}"
