---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Setup Scrypted directory
  ansible.builtin.file:
    path: "{{ scrypted_folder }}"
    state: directory
    mode: '0755'
    owner: qnapadmin
    group: qnapadmin

- name: Setup Scrypted config directory
  ansible.builtin.file:
    path: "{{ scrypted_folder }}/volume"
    state: directory
    mode: '0755'
    owner: qnapadmin
    group: qnapadmin

- name: Setup the NVR storage directory
  ansible.builtin.file:
    path: "{{ scrypted_folder }}/nvr"
    state: directory
    mode: '0755'
    owner: qnapadmin
    group: qnapadmin

- name: Deploy Scrypted using Docker Compose
  ansible.builtin.template:
    src: "templates/docker_compose.yaml.j2"
    dest: "{{ scrypted_folder }}/docker-compose.yaml"
    mode: '0644'
    owner: qnapadmin
    group: qnapadmin
  notify:
    - Start Scrypted

- name: Run Scrypted docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ scrypted_folder }}"
    state: present
    remote_orphans: false

# Scrypted web UI (host networking, optional)
- name: Allow Scrypted web UI port through UFW (if set)
  community.general.ufw:
    rule: allow
    port: "{{ scrypted_port | default(omit) }}"
    proto: tcp
  when:
    - ansible_os_family == "Debian"
    - scrypted_port is defined

# Check if Scrypted port is open and listening (if defined)
- name: Check if Scrypted port is open and listening
  community.general.listen_ports_facts:

- name: Assert Scrypted port is listening (if defined)
  ansible.builtin.assert:
    that:
      - scrypted_port is not defined or scrypted_port | int in (ansible_facts.tcp_listen | map(attribute='port') | list)
    fail_msg: "Scrypted port {{ scrypted_port }} is not open and listening!"
    success_msg: "Scrypted port {{ scrypted_port }} is open and listening."
