---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Get fileserver IP
  ansible.builtin.set_fact:
    paperless_fileserver_ip: "{{ (lookup('ansible.builtin.inventory_hostnames', 'qnap').split(','))[0] }}"

- name: Get proxy IP
  ansible.builtin.set_fact:
    paperless_trusted_proxies: "{{ (lookup('ansible.builtin.inventory_hostnames', 'proxy').split(','))[0] }}"

- name: Setup directory
  ansible.builtin.file:
    path: "{{ paperless_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Allow Paperless port through UFW
  community.general.ufw:
    rule: allow
    port: "{{ paperless_port }}"
    proto: tcp
  when: ansible_os_family == "Debian"

- name: Deploy Paperless using Docker Compose
  ansible.builtin.template:
    src: "templates/docker_compose.yaml.j2"
    dest: "{{ paperless_folder }}/docker-compose.yaml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true
  notify:
    - Start Paperless

- name: Run Paperless docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ paperless_folder }}"
    state: present
    remove_orphans: true

# Check if Paperless port is open and listening
- name: Check if Paperless port is open and listening
  community.general.listen_ports_facts:

- name: Assert Paperless port is listening
  ansible.builtin.assert:
    that:
      - paperless_port | int in (ansible_facts.tcp_listen | map(attribute='port') | list)
    fail_msg: "Paperless port {{ paperless_port }} is not open and listening!"
    success_msg: "Paperless port {{ paperless_port }} is open and listening."

# Proxy Configuration
- name: Configure nginx proxy for paperless
  when: configure_proxy | default(true)
  block:
    - name: Get paperless host IP for proxy
      ansible.builtin.set_fact:
        paperless_proxy_ip: "{{ ansible_default_ipv4.address }}"

    - name: Deploy paperless nginx proxy config
      ansible.builtin.template:
        src: "templates/paperless.subdomain.conf.j2"
        dest: "{{ proxy_folder }}/internal/nginx/proxy-confs/paperless.subdomain.conf"
        mode: '0644'
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
      delegate_to: "{{ groups['proxy_host'][0] }}"
      notify: Restart Swag

    - name: Debug proxy configuration
      ansible.builtin.debug:
        msg: >-
          Paperless proxy config deployed to {{ groups['proxy_host'][0] }}
          routing {{ paperless_proxy_ip }}:{{ paperless_port }} -> https://paperless.{{ internal_domain }}

# Homepage Configuration
- name: Check if paperless service already exists in services.yaml
  ansible.builtin.command:
    cmd: grep -q "Paperless-NGX" {{ homepage_folder }}/config/services.yaml
  delegate_to: "{{ groups['homepage_host'][0] }}"
  register: paperless_in_homepage
  failed_when: false
  changed_when: false
  when: configure_homepage | default(false)

- name: Add paperless service to Homepage Smart Home section
  ansible.builtin.blockinfile:
    path: "{{ homepage_folder }}/config/services.yaml"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - paperless"
    insertafter: "- Smart Home:"
    block: "{{ lookup('template', 'homepage_service.yaml.j2') }}"
  delegate_to: "{{ groups['homepage_host'][0] }}"
  when:
    - configure_homepage | default(false)
    - paperless_in_homepage.rc != 0
  notify: Restart Homepage
