---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Get fileserver IP
  ansible.builtin.set_fact:
    paperless_fileserver_ip: "{{ (lookup('ansible.builtin.inventory_hostnames', 'qnap').split(','))[0] }}"

- name: Get proxy IP
  ansible.builtin.set_fact:
    paperless_trusted_proxies: "{{ (lookup('ansible.builtin.inventory_hostnames', 'proxy').split(','))[0] }}"

- name: Setup directory
  ansible.builtin.file:
    path: "{{ paperless_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Deploy Paperless using Docker Compose
  ansible.builtin.template:
    src: "templates/docker_compose.yaml.j2"
    dest: "{{ paperless_folder }}/docker-compose.yaml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true
  notify:
    - Start Paperless

- name: Run Paperless docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ paperless_folder }}"
    state: present
    remove_orphans: true

