---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Get fileserver IP
  ansible.builtin.set_fact:
    paperless_fileserver_ip: "{{ (lookup('ansible.builtin.inventory_hostnames', 'qnap').split(','))[0] }}"

- name: Get proxy IP
  ansible.builtin.set_fact:
    paperless_trusted_proxies: "{{ (lookup('ansible.builtin.inventory_hostnames', 'proxy').split(','))[0] }}"

- name: Setup directory
  ansible.builtin.file:
    path: "{{ paperless_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Allow Paperless port through UFW
  community.general.ufw:
    rule: allow
    port: "{{ paperless_port }}"
    proto: tcp
  when: ansible_os_family == "Debian"

- name: Deploy Paperless using Docker Compose
  ansible.builtin.template:
    src: "templates/docker_compose.yaml.j2"
    dest: "{{ paperless_folder }}/docker-compose.yaml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true
  notify:
    - Start Paperless

- name: Run Paperless docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ paperless_folder }}"
    state: present
    remove_orphans: true

# Check if Paperless port is open and listening
- name: Check if Paperless port is open and listening
  community.general.listen_ports_facts:

- name: Assert Paperless port is listening
  ansible.builtin.assert:
    that:
      - paperless_port | int in (ansible_facts.tcp_listen | map(attribute='port') | list)
    fail_msg: "Paperless port {{ paperless_port }} is not open and listening!"
    success_msg: "Paperless port {{ paperless_port }} is open and listening."

# Proxy Configuration
- name: Configure nginx proxy for paperless
  when: paperless_configure_proxy | default(true)
  block:
    - name: Get paperless host IP for proxy
      ansible.builtin.set_fact:
        paperless_proxy_ip: "{{ ansible_default_ipv4.address }}"

    - name: Deploy paperless nginx proxy config
      ansible.builtin.template:
        src: "templates/paperless.subdomain.conf.j2"
        dest: "{{ proxy_folder }}/internal/nginx/proxy-confs/paperless.subdomain.conf"
        mode: '0644'
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
      delegate_to: "{{ groups['proxy_host'][0] }}"
      notify: Restart Swag

# DNS Configuration
- name: Get DNS resolver host overrides from pfSense
  ansible.builtin.uri:
    url: "https://{{ groups['pfsense_host'][0] }}/api/v2/services/dns_resolver/host_overrides"
    method: GET
    headers:
      X-API-Key: "{{ pfsense_api_key }}"
    validate_certs: false
    return_content: true
  register: pfsense_dns_overrides
  delegate_to: localhost
  when: paperless_configure_dns | default(true)

- name: Find proxy host override entry in pfSense
  ansible.builtin.set_fact:
    proxy_host_override: >-
      {{ pfsense_dns_overrides.json.data
         | selectattr('host', 'equalto', 'proxy')
         | selectattr('domain', 'equalto', internal_domain)
         | list
         | first
         | default({}) }}
  when:
    - paperless_configure_dns | default(true)
    - pfsense_dns_overrides.json.data is defined

- name: Check if paperless alias exists under proxy host override
  ansible.builtin.set_fact:
    paperless_alias_exists: >-
      {{ proxy_host_override.aliases | default([])
         | selectattr('host', 'equalto', 'paperless')
         | selectattr('domain', 'equalto', internal_domain)
         | list
         | length > 0 }}
  when:
    - paperless_configure_dns | default(true)
    - proxy_host_override is defined
    - proxy_host_override | length > 0

- name: Display paperless DNS alias status
  ansible.builtin.debug:
    msg: >-
      {% if proxy_host_override | length == 0 %}
      Warning: Proxy host override not found in pfSense DNS
      {% elif paperless_alias_exists %}
      Paperless DNS alias exists under proxy.{{ internal_domain }}
      {% else %}
      Paperless DNS alias missing - will be created
      {% endif %}
  when: paperless_configure_dns | default(true)

- name: Create paperless DNS alias under proxy host override
  ansible.builtin.uri:
    url: "https://{{ groups['pfsense_host'][0] }}/api/v2/services/dns_resolver/host_override/alias"
    method: POST
    headers:
      X-API-Key: "{{ pfsense_api_key }}"
      Content-Type: "application/json"
    body_format: json
    body:
      parent_id: "{{ proxy_host_override.id }}"
      host: "paperless"
      domain: "{{ internal_domain }}"
      descr: "Paperless-NGX document management"
    validate_certs: false
    status_code: [200, 201]
  delegate_to: localhost
  register: alias_creation_result
  when:
    - paperless_configure_dns | default(true)
    - proxy_host_override | length > 0
    - not paperless_alias_exists

- name: Apply DNS resolver changes in pfSense
  ansible.builtin.uri:
    url: "https://{{ groups['pfsense_host'][0] }}/api/v2/services/dns_resolver/apply"
    method: POST
    headers:
      X-API-Key: "{{ pfsense_api_key }}"
    validate_certs: false
    status_code: [200, 201]
  delegate_to: localhost
  when:
    - paperless_configure_dns | default(true)
    - alias_creation_result is succeeded

# Homepage Configuration
- name: Add paperless service to Homepage Smart Home section
  ansible.builtin.blockinfile:
    path: "{{ homepage_folder }}/config/services.yaml"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - paperless"
    insertafter: "- Smart Home:"
    block: "{{ lookup('template', 'homepage_service.yaml.j2') }}"
  delegate_to: "{{ groups['homepage_host'][0] }}"
  notify: Restart Homepage
  when: paperless_configure_homepage | default(true)
  tags:
    - homepage
    - homepage_config
