---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Setup Homepage directory
  ansible.builtin.file:
    path: "{{ homepage_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Setup Homepage config directory
  ansible.builtin.file:
    path: "{{ homepage_folder }}/config"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Allow Homepage port through UFW
  community.general.ufw:
    rule: allow
    port: "{{ homepage_port }}"
    proto: tcp
  when: ansible_os_family == "Debian"

- name: Deploy Bookmarks config
  ansible.builtin.template:
    src: "templates/bookmarks.yaml.j2"
    dest: "{{ homepage_folder }}/config/bookmarks.yaml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true

- name: Deploy Docker config
  ansible.builtin.template:
    src: "templates/docker.yaml.j2"
    dest: "{{ homepage_folder }}/config/docker.yaml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true

- name: Deploy Kubernetes config
  ansible.builtin.template:
    src: "templates/kubernetes.yaml.j2"
    dest: "{{ homepage_folder }}/config/kubernetes.yaml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true

- name: Deploy Services config
  ansible.builtin.template:
    src: "templates/services.yaml.j2"
    dest: "{{ homepage_folder }}/config/services.yaml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true

- name: Deploy Settings config
  ansible.builtin.template:
    src: "templates/settings.yaml.j2"
    dest: "{{ homepage_folder }}/config/settings.yaml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true

- name: Deploy Widgets config
  ansible.builtin.template:
    src: "templates/widgets.yaml.j2"
    dest: "{{ homepage_folder }}/config/widgets.yaml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true


- name: Deploy Homepage using Docker Compose
  ansible.builtin.template:
    src: "templates/docker_compose.yaml.j2"
    dest: "{{ homepage_folder }}/docker-compose.yaml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
  notify:
    - Start Homepage

- name: Run Homepage docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ homepage_folder }}"
    state: present
    remove_orphans: false

- name: Check if Homepage port is open and listening
  community.general.listen_ports_facts:

- name: Assert Homepage port is listening
  ansible.builtin.assert:
    that:
      - homepage_port | int in (ansible_facts.tcp_listen | map(attribute='port') | list)
    fail_msg: "Homepage port {{ homepage_port }} is not open and listening!"
    success_msg: "Homepage port {{ homepage_port }} is open and listening."

# Proxy Configuration
- name: Configure nginx proxy for homepage
  when: homepage_configure_proxy | default(true)
  block:
    - name: Get homepage host IP for proxy
      ansible.builtin.set_fact:
        homepage_proxy_ip: "{{ ansible_default_ipv4.address }}"

    - name: Deploy homepage nginx proxy config
      ansible.builtin.template:
        src: "templates/homepage.subdomain.conf.j2"
        dest: "{{ proxy_folder }}/internal/nginx/proxy-confs/homepage.subdomain.conf"
        mode: '0644'
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
      delegate_to: "{{ groups['proxy_host'][0] }}"
      notify: Restart Swag

    - name: Debug proxy configuration
      ansible.builtin.debug:
        msg: >-
          Homepage proxy config deployed to {{ groups['proxy_host'][0] }}
          routing {{ homepage_proxy_ip }}:{{ homepage_port }} -> https://homepage.{{ internal_domain }}
