---
# Research Notes - Homepage
# Official Source: https://gethomepage.dev/
# Docker Hub: https://hub.docker.com/r/ghcr.io/gethomepage/homepage
# Default Port: 3000
# Last Updated: 2025-10-09

homepage_version: "latest"

# External port
homepage_port: 3000

# Custom service icons
homepage_bambuddy_icon_url: "https://raw.githubusercontent.com/maziggy/bambuddy/3dcbbdd25e5a86ba267357e7fa4397c5a6569784/static/img/android-chrome-512x512.png"
homepage_bambuddy_icon_checksum: "sha256:cd1c375e5018c627a5782618c02c92e018b769f8481e37479c036bc9680e4ccb"

# Feature flags
homepage_configure_proxy: true
homepage_configure_dns: true
homepage_configure_homepage: false  # N/A - homepage doesn't add itself
