---
# Tasks for initial OS configuration
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
  when: ansible_os_family == "Debian"

- name: Set UFW default incoming policy to deny
  community.general.ufw:
    direction: incoming
    policy: deny
  when: ansible_os_family == "Debian"

- name: Set UFW default outgoing policy to allow
  community.general.ufw:
    direction: outgoing
    policy: allow
  when: ansible_os_family == "Debian"

- name: Allow SSH through UFW
  community.general.ufw:
    rule: allow
    name: OpenSSH
  when: ansible_os_family == "Debian"

- name: Allow Node Exporter port through UFW
  community.general.ufw:
    rule: allow
    port: 9100
    proto: tcp
  when: ansible_os_family == "Debian"

- name: Enable UFW
  community.general.ufw:
    state: enabled
  when: ansible_os_family == "Debian"

- name: Ensure fail2ban is installed
  ansible.builtin.apt:
    name: fail2ban
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure fail2ban is started and enabled
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

- name: Harden SSH - Disable root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
    create: true
  notify: Restart SSH
  when: ansible_os_family == "Debian"
  become: true

- name: Harden SSH - Disable password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    create: true
  notify: Restart SSH
  when: ansible_os_family == "Debian"

- name: Harden SSH - Allow only key-based authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication'
    line: 'ChallengeResponseAuthentication no'
    state: present
    create: true
  notify: Restart SSH
  when: ansible_os_family == "Debian"

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"
  when: ansible_os_family == "Debian"

- name: Configure locale
  community.general.locale_gen:
    name: "{{ locale_lang }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Set system locale
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: "LANG={{ locale_lang }}"
    create: true
    mode: '0644'
  when: ansible_os_family == "Debian"

- name: Remove ntp if present
  ansible.builtin.apt:
    name: ntp
    state: absent
    purge: true
  when: ansible_os_family == "Debian"

- name: Ensure chrony is installed
  ansible.builtin.apt:
    name: chrony
    state: present
  when: ansible_os_family == "Debian"

- name: Deploy chrony configuration
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart chrony
  when: ansible_os_family == "Debian"

- name: Ensure chrony is started and enabled
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true
