---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Setup Parent directory
  ansible.builtin.file:
    path: "{{ grafana_parent_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Ensure Loki data directory exists
  ansible.builtin.file:
    path: "{{ loki_data_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Ensure Prometheus data directory exists
  ansible.builtin.file:
    path: "{{ prometheus_data_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Allow Grafana port through UFW
  ufw:
    rule: allow
    port: "{{ grafana_port }}"
    proto: tcp
  when: ansible_os_family == "Debian"

- name: Allow Loki port through UFW
  ufw:
    rule: allow
    port: "{{ grafana_loki_port }}"
    proto: tcp
  when: ansible_os_family == "Debian"

- name: Allow Prometheus port through UFW
  ufw:
    rule: allow
    port: "{{ grafana_prometheus_port }}"
    proto: tcp
  when: ansible_os_family == "Debian"

- name: Deploy Prometheus config
  ansible.builtin.template:
    src: "templates/prometheus.yml.j2"
    dest: "{{ grafana_parent_folder }}/prometheus.yml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true

- name: Deploy Grafana using Docker Compose
  ansible.builtin.template:
    src: "templates/docker_compose.yaml.j2"
    dest: "{{ grafana_parent_folder }}/docker-compose.yaml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true
  notify:
    - Start Grafana

- name: Run docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_parent_folder }}"
    state: present
    remove_orphans: true

- name: Ensure Grafana provisioning directory exists
  ansible.builtin.file:
    path: "{{ grafana_parent_folder }}/provisioning/datasources"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Deploy Grafana datasources provisioning config
  ansible.builtin.template:
    src: "templates/provisioning_datasources.yaml.j2"
    dest: "{{ grafana_parent_folder }}/provisioning/datasources/datasources.yaml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true

# Check if Grafana stack ports are open and listening
- name: Check if Grafana stack ports are open and listening
  community.general.listen_ports_facts:

- name: Assert Grafana stack ports are listening
  ansible.builtin.assert:
    that:
      - grafana_port | int in (ansible_facts.tcp_listen | map(attribute='port') | list)
      - grafana_loki_port | int in (ansible_facts.tcp_listen | map(attribute='port') | list)
      - grafana_prometheus_port | int in (ansible_facts.tcp_listen | map(attribute='port') | list)
    fail_msg: "One or more Grafana stack ports are not open and listening!"
    success_msg: "All Grafana stack ports are open and listening."