---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Setup Grafana directory
  ansible.builtin.file:
    path: "{{ grafana_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Setup Loki directory
  ansible.builtin.file:
    path: "{{ grafana_loki_data_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Setup Prometheus directory
  ansible.builtin.file:
    path: "{{ grafana_prometheus_data_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Ensure Loki data directory exists
  ansible.builtin.file:
    path: "{{ grafana_loki_data_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Ensure Prometheus data directory exists
  ansible.builtin.file:
    path: "{{ grafana_prometheus_data_folder }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Allow Grafana port through UFW
  community.general.ufw:
    rule: allow
    port: "{{ grafana_port }}"
    proto: tcp
  when: ansible_os_family == "Debian"

- name: Allow Loki port through UFW
  community.general.ufw:
    rule: allow
    port: "{{ grafana_loki_port }}"
    proto: tcp
  when: ansible_os_family == "Debian"

- name: Allow Prometheus port through UFW
  community.general.ufw:
    rule: allow
    port: "{{ grafana_prometheus_port }}"
    proto: tcp
  when: ansible_os_family == "Debian"

- name: Deploy Prometheus config
  ansible.builtin.template:
    src: "templates/prometheus.yml.j2"
    dest: "{{ grafana_prometheus_data_folder }}/prometheus.yml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true

- name: Deploy Grafana using Docker Compose
  ansible.builtin.template:
    src: "templates/docker_compose.yaml.j2"
    dest: "{{ grafana_parent_folder }}/docker-compose.yaml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true
  notify:
    - Start Grafana

- name: Run docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_parent_folder }}"
    state: present
    remove_orphans: true

- name: Ensure Grafana provisioning directory exists
  ansible.builtin.file:
    path: "{{ grafana_folder }}/provisioning/datasources"
    state: directory
    mode: '0755'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: Deploy Grafana datasources provisioning config
  ansible.builtin.template:
    src: "templates/provisioning_datasources.yaml.j2"
    dest: "{{ grafana_folder }}/provisioning/datasources/datasources.yaml"
    mode: '0644'
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    force: true

# Check if Grafana stack ports are open and listening
- name: Check if Grafana stack ports are open and listening
  community.general.listen_ports_facts:

- name: Assert Grafana stack ports are listening
  ansible.builtin.assert:
    that:
      - grafana_port | int in (ansible_facts.tcp_listen | map(attribute='port') | list)
      - grafana_loki_port | int in (ansible_facts.tcp_listen | map(attribute='port') | list)
      - grafana_prometheus_port | int in (ansible_facts.tcp_listen | map(attribute='port') | list)
    fail_msg: "One or more Grafana stack ports are not open and listening!"
    success_msg: "All Grafana stack ports are open and listening."

# Configure SWAG Internal Proxy
- name: Resolve grafana host IP for proxy configuration
  ansible.builtin.set_fact:
    grafana_proxy_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  when: grafana_configure_proxy | default(true)

- name: Deploy Grafana nginx config to SWAG Internal
  ansible.builtin.template:
    src: grafana.subdomain.conf.j2
    dest: "{{ proxy_folder }}/internal/nginx/proxy-confs/grafana.subdomain.conf"
    mode: '0644'
  delegate_to: "{{ groups['proxy_host'][0] }}"
  notify:
    - Restart Swag
  when: grafana_configure_proxy | default(true)

# Check pfSense DNS Resolver Host Overrides
- name: Get DNS resolver host overrides from pfSense
  ansible.builtin.uri:
    url: "https://{{ groups['pfsense_host'][0] }}/api/v2/services/dns_resolver/host_overrides"
    method: GET
    headers:
      X-API-Key: "{{ pfsense_api_key }}"
    validate_certs: false
    return_content: true
  register: pfsense_dns_overrides
  delegate_to: localhost
  when: grafana_configure_dns | default(true)

- name: Find proxy host override entry in pfSense
  ansible.builtin.set_fact:
    proxy_host_override: >-
      {{ pfsense_dns_overrides.json.data
         | selectattr('host', 'equalto', 'proxy')
         | selectattr('domain', 'equalto', internal_domain)
         | list
         | first
         | default({}) }}
  when:
    - grafana_configure_dns | default(true)
    - pfsense_dns_overrides.json.data is defined

- name: Check if Grafana alias exists under proxy host override
  ansible.builtin.set_fact:
    grafana_alias_exists: >-
      {{ proxy_host_override.aliases | default([])
         | selectattr('host', 'equalto', 'grafana')
         | selectattr('domain', 'equalto', internal_domain)
         | list
         | length > 0 }}
  when:
    - grafana_configure_dns | default(true)
    - proxy_host_override is defined
    - proxy_host_override | length > 0

- name: Display Grafana DNS alias status
  ansible.builtin.debug:
    msg: >-
      {% if proxy_host_override | length == 0 %}
      Warning: Proxy host override not found in pfSense DNS
      {% elif grafana_alias_exists %}
      Grafana DNS alias exists under proxy.{{ internal_domain }}
      {% else %}
      Grafana DNS alias missing - will be created
      {% endif %}
  when: grafana_configure_dns | default(true)

- name: Create Grafana DNS alias under proxy host override
  ansible.builtin.uri:
    url: "https://{{ groups['pfsense_host'][0] }}/api/v2/services/dns_resolver/host_override/alias"
    method: POST
    headers:
      X-API-Key: "{{ pfsense_api_key }}"
      Content-Type: "application/json"
    body_format: json
    body:
      parent_id: "{{ proxy_host_override.id }}"
      host: "grafana"
      domain: "{{ internal_domain }}"
      descr: "Grafana monitoring dashboard"
    validate_certs: false
    status_code: [200, 201]
  delegate_to: localhost
  register: alias_creation_result
  when:
    - grafana_configure_dns | default(true)
    - proxy_host_override | length > 0
    - not grafana_alias_exists

- name: Apply DNS resolver changes in pfSense
  ansible.builtin.uri:
    url: "https://{{ groups['pfsense_host'][0] }}/api/v2/services/dns_resolver/apply"
    method: POST
    headers:
      X-API-Key: "{{ pfsense_api_key }}"
    validate_certs: false
    status_code: [200, 201]
  delegate_to: localhost
  when:
    - grafana_configure_dns | default(true)
    - alias_creation_result is succeeded

# Configure Homepage Services
- name: Add grafana service to Homepage Infra section
  ansible.builtin.blockinfile:
    path: "{{ homepage_folder }}/config/services.yaml"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - grafana service"
    block: "{{ lookup('template', 'homepage_service.yaml.j2') }}"
    insertafter: "^- Infra:"
    mode: '0644'
  delegate_to: "{{ groups['homepage_host'][0] }}"
  notify:
    - Restart Homepage
  when: grafana_configure_homepage | default(true)
