---
# Alloy - Grafana log collection agent
# Official Source: https://grafana.com/docs/alloy/latest/
# Docker Hub: https://hub.docker.com/r/grafana/alloy
# Last Updated: 2026-03-25

alloy_version: "latest"
alloy_folder: "{{ docker_storage_folder }}/alloy"
alloy_loki_url: "http://{{ groups['grafana_host'][0] }}.{{ internal_domain }}:3100/loki/api/v1/push"
