---
- name: Set Docker apt repository for correct distribution
  ansible.builtin.set_fact:
    docker_apt_repository: >-
      {{
        'deb [arch=amd64] https://download.docker.com/linux/ubuntu ' ~ ansible_distribution_release ~ ' stable'
        if ansible_distribution == 'Ubuntu'
        else 'deb [arch=amd64] https://download.docker.com/linux/debian ' ~ ansible_distribution_release ~ ' stable'
      }}

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Ensure the docker user group exists for LinuxServer containers
  ansible.builtin.group:
    name: "{{ docker_user }}"
    state: present
    gid: 2001

- name: Add the docker user to the group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    comment: Docker User
    uid: 2001
    group: "{{ docker_user }}"

- name: Create Docker data folder
  ansible.builtin.file:
    path: /etc/docker-storage
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: "0755"

- name: Ensure apt is using HTTPS
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ 'ubuntu' if ansible_distribution == 'Ubuntu' else 'debian' }}/gpg"
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    filename: docker
    update_cache: true

- name: Install Docker CE
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Configure Docker daemon options
  ansible.builtin.template:
    src: "templates/docker_daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: Restart Docker

- name: Ensure Docker service is enabled and running
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
