---
- name: Install Docker
  hosts: sonarr_host
  become: true
  roles:
    - docker

- name: Install the *arr suite
  hosts: sonarr_host
  become: true
  roles:
    - arr_suite

- name: Install NGINX
  hosts: proxy_host
  become: true
  roles:
    - proxy
