---
- name: Initial OS Configuration
  ansible.builtin.import_playbook: os_setup.yaml

- name: Configure Proxmox Hosts
  ansible.builtin.import_playbook: deploy_proxmox.yaml

- name: Deploy Proxy
  ansible.builtin.import_playbook: deploy_proxy.yaml

- name: Deploy Homepage
  ansible.builtin.import_playbook: deploy_homepage.yaml

- name: Deploy Maintainerr
  ansible.builtin.import_playbook: deploy_maintainerr.yaml

- name: Deploy Arr Suite
  ansible.builtin.import_playbook: deploy_arr.yaml

- name: Deploy Plex
  ansible.builtin.import_playbook: deploy_plex.yaml

# - name: Deploy Jellyfin
#   ansible.builtin.import_playbook: deploy_jellyfin.yaml

- name: Deploy Jellyseerr
  ansible.builtin.import_playbook: deploy_jellyseerr.yaml

- name: Deploy Grafana
  ansible.builtin.import_playbook: deploy_grafana.yaml

- name: Deploy n8n
  ansible.builtin.import_playbook: deploy_n8n.yaml

- name: Deploy Paperless
  ansible.builtin.import_playbook: deploy_paperless.yaml

- name: Deploy Tracearr
  ansible.builtin.import_playbook: deploy_tracearr.yaml
