---
- name: Initial OS Configuration
  ansible.builtin.import_playbook: os_setup.yaml

- name: Deploy Proxy
  ansible.builtin.import_playbook: deploy_proxy.yaml

- name: Deploy Homepage
  ansible.builtin.import_playbook: deploy_homepage.yaml

- name: Deploy Arr Suite
  ansible.builtin.import_playbook: deploy_arr.yaml

- name: Deploy Plex
  ansible.builtin.import_playbook: deploy_plex.yaml

- name: Deploy Jellyfin
  ansible.builtin.import_playbook: deploy_jellyfin.yaml

- name: Deploy Jellyseerr
  ansible.builtin.import_playbook: deploy_jellyseerr.yaml

- name: Deploy Grafana
  ansible.builtin.import_playbook: deploy_grafana.yaml

- name: Deploy n8n
  ansible.builtin.import_playbook: deploy_n8n.yaml

- name: Deploy Paperless
  ansible.builtin.import_playbook: deploy_paperless.yaml

- name: Install Prometheus Node Exporter
  hosts: ubuntu
  become: true
  roles:
    - role: prometheus.prometheus.node_exporter
