---
- name: Initial OS Configuration
  hosts: ubuntu:debian
  become: true
  roles:
    - os_configure
    - docker

- name: Install KDE Plasma Desktop and xrdp
  hosts: linux_desktop
  become: true
  roles:
    - kde_desktop
